apiVersion: apps/v1
kind: Deployment
metadata:
  name: kindness-wall-deployment
  labels:
    app: kindness-wall
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kindness-wall
  template:
    metadata:
      labels:
        app: kindness-wall
    spec:
      containers:
        - name: kindness-wall
          image: mahrukh26/kindness-wall:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: kindness-secret
                  key: mongodb-uri
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
